apiVersion: apps/v1
kind: Deployment
metadata:
  name: innodeploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innodeploy
  template:
    metadata:
      labels:
        app: innodeploy
    spec:
      containers:
      - name: app
        image: nourhenhachem/innodeploy-app:v1777851660
        ports:
        - containerPort: 3000
